name: ixiamobile_application
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.2"

dependencies:
  http: ^0.12.2
  curved_navigation_bar: ^0.3.3
  json_annotation: ^3.0.1
  font_awesome_flutter: ^8.5.0
  dio: ^3.0.10
  shared_preferences: ^0.5.6
  cupertino_icons: ^0.1.3
  provider: ^4.3.2
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.0.2
  google_maps_flutter: ^0.5.31
  location: ^2.5.4
  flutter_polyline_points: ^0.1.0
  flutter_rating_bar: ^3.0.1+1
  geolocator: ^5.1.5
  image_picker: ^0.6.7+8
  http_parser: ^3.1.4
  flutter_launcher_icons: ^0.8.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^1.0.3
  json_serializable: ^3.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "res/images/IXIA.png"

flutter:

  uses-material-design: true

  assets:
    - res/images/
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: res/fonts/Montserrat-Regular.ttf
  
module:
  android.useAndroidX=true
  android.enableJetifier=true